Implementation eslint with rules
bitRocket-dev/reactJS-app-boilerplate pull request #2
Opened 2023-03-21 14:36 UTC by cristianpalermo-bitrocketdev

## Descrizione

Implementazione esLint con regole

## Commenti da segnalare

_Indica se ci sono cose da sapere prima di effettuare la review_

## Tipologia dell modifica - indica una o più opzioni

- [ ] 🐛 Bug fix (no breaking change)
- [x] 🆕 New feature (no breaking - aggiunge una funzionalità)
- [ ] 💄 Adjustment (modifica grafica o logica business)
- [ ] 💥 Breaking change (bug fix o aggiunge una funzionalità che potrebbe non essere supportare sulle versione precedenti)

## Testat su - indica uno o più dispositivi

- [x] Chrome
- [ ] Explorer
- [ ] Safari
- [ ] Firefox

## Come effettuare un test - indica uno o più test per la verifica

_Aggiungi informazioni utili per facilitare il test all'utente_

### Screenshots o video 📸 👇

2023-03-21 16:37 UTC, riccardogenova-bitrocketdev commented on .eslintrc.json
> +  "plugins": ["react"],
ne mancano una serie che utilizziamo solitamente

2023-03-21 16:38 UTC, riccardogenova-bitrocketdev commented on .eslintrc.json
> +  "plugins": ["react"],
e che hai integrato come devDependency ma che non stai utilizzando

2023-03-22 09:56 UTC, riccardogenova-bitrocketdev requested changes

2023-03-22 09:56 UTC, riccardogenova-bitrocketdev commented on package.json
> +    "eslint-plugin-n": "^15.6.1",
che roba è ?

2023-03-22 09:56 UTC, riccardogenova-bitrocketdev commented on package.json
> +    "@babel/core": "^7.21.3",
a cosa servono ?

2023-03-22 09:56 UTC, riccardogenova-bitrocketdev commented on package.json
> +    "@testing-library/dom": "^9.0.1",
ci sono librerie che non mi pare abbiano a che fare con eslint...

2023-03-22 09:56 UTC, riccardogenova-bitrocketdev commented on package.json
> +    "test:lint": "eslint --ext .ts,.tsx"
alla configurazione di eslint dovremmo aggiungere anche la configurazione dei tipi. 
Eslint viene utilizzato per gestire anche gli errori Typescriot di conseguenza occorre aggiungere lo script (test:type) e verificare la configurazione del tsconfig

2023-03-22 10:22 UTC, cristianpalermo-bitrocketdev commented on package.json
> +    "@babel/core": "^7.21.3",
BabelJS trasforma il codice di ECMAScript nuovo in versioni compatibili coi precedenti ECMAScript. non serve con esLint in se, quindi rimuovo e si fa una task a parte per questo

2023-03-23 12:37 UTC, riccardogenova-bitrocketdev approved these changes

2023-03-23 12:38 UTC, merged