feat: add lint-staged & husky
bitRocket-dev/reactJS-app-boilerplate pull request #4
Opened 2023-03-21 16:56 UTC by cristianpalermo-bitrocketdev

## Descrizione

Aggiunta configurazione per hushy e commitlint

## Tipologia dell modifica - indica una o più opzioni

- [ ] 🐛 Bug fix (no breaking change)
- [x] 🆕 New feature (no breaking - aggiunge una funzionalità)
- [ ] 💄 Adjustment (modifica grafica o logica business)
- [ ] 💥 Breaking change (bug fix o aggiunge una funzionalità che potrebbe non essere supportare sulle versione precedenti)

## Testat su - indica uno o più dispositivi

- [x] Chrome
- [ ] Explorer
- [ ] Safari
- [ ] Firefox

## Come effettuare un test - indica uno o più test per la verifica

_Aggiungi informazioni utili per facilitare il test all'utente_

### Screenshots o video 📸 👇

2023-03-21 17:06 UTC, riccardogenova-bitrocketdev commented on package.json
> +    "husky": "^8.0.3",
devDependency

2023-03-21 17:07 UTC, riccardogenova-bitrocketdev commented on package.json
> +      "yarn test:type",
Mancano gli scripts

2023-03-22 10:00 UTC, riccardogenova-bitrocketdev requested changes

2023-03-22 10:00 UTC, riccardogenova-bitrocketdev commented on package.json
> +      "yarn format"
lo script non esiste

2023-03-22 12:26 UTC, cristianpalermo-bitrocketdev commented on package.json
> +      "yarn format"
avrei bisogno di ulteriori chiarimenti

2023-03-27 15:45 UTC, riccardogenova-bitrocketdev submitted a review, later dismissed

2023-03-27 15:47 UTC, merged